### ISSUE TITLE
[CHORE] - Better url for CNBC

### ISSUE THREAD

**Issue by MizouziE** [MizouziE/energy-prices-api#104]
### What work needs to be performed?

inside the sources file src/data/sources.json around line 47, please change the following:

```json
  {
    "name": "CNBC",
    "site": "https://www.cnbc.com/world/",
    "base": ""
  },
```

to:

```json
  {
    "name": "CNBC",
    "site": "https://www.cnbc.com/energy/",
    "base": ""
  },
```

### Additional information

This is just because I noticed energy price related articles were no longer being published in the world section of the site and found more useful articles in the energy section.

**Comment by nomandhoni-cs** [comment]
@MizouziE I fixed and made a pull request. Please have a look https://github.com/MizouziE/energy-prices-api/pull/105#issue-1335964796
