### ISSUE TITLE
[CHORE] - add to keywords

### ISSUE THREAD

**Issue by MizouziE** [MizouziE/energy-prices-api#109]
### What work needs to be performed?

Let's add some more to the list in `src/data/keywords.js`:

- gas prices
- petrol prices

### Additional information

Seems to be a related hot-topic

**Comment by mrajen27** [comment]
Team, I will work on this and raise an PR.

**Comment by MizouziE** [comment]
> Team, I will work on this and raise an PR.

Hey @mrajen27 thanku, but I missed closing this issue with a PR that was merged a few hours ago. 

We still need some help on #107 and #108 if you'd like to contribute?

**Comment by mrajen27** [comment]
Yes sure I will work on it and raise the PR
