### ISSUE TITLE
Thumbnail image

### ISSUE THREAD

**Issue by MizouziE** [MizouziE/energy-prices-api#16]
If someone were to use the API and need a thumbnail for display purposes, what would be a good way to get one from the link/source?

**Comment by TAKANOME-DEV** [comment]
Hey @MizouziE if you can get the image, you can use [sharp](https://www.npmjs.com/package/sharp) to resize it 😉

**Comment by MizouziE** [comment]
Hey @TAKANOME-DEV, to be honest I was only really thinking to provide an image url that a user could then use as a source and manipulate as they see fit. 

The question really is how to "universally" find the right <img> element to scrape the `src="..."` from?

The answer may even be in the [documentation for cheerio](https://cheerio.js.org/) that I haven't read fully myself yet.

**Comment by TAKANOME-DEV** [comment]
This one seems tricky, isn't that what you have assigned in #18 ??

**Comment by MizouziE** [comment]
@TAKANOME-DEV Over in #18 the value coming back was a whole image tag that we didn't actually want there, that particular site just used an image instead of a h1 title which lead to the generic approach tripping over it. What I'd like is an *additional* key value pair in the article object exclusively for an image url. 
The real tricky bit is gonna be figuring how to find the right image in a generic way 🙃

**Comment by TAKANOME-DEV** [comment]
Absolutely, I tried to get the parentNode of the `a` tag and then grap the `image/source` tag `src/srcset` attribute, but I can't get it 😂 

I never used Jquery, maybe that's why it's tough for me 😄

**Comment by MizouziE** [comment]
I definitely think this one will take some experimentation, or perhaps we'll be lucky and get some input from a new contributor.

Don't worry about your jQuery skills, I barely have any ability with JavaScript at all! 😅😂😂

**Comment by MizouziE** [comment]
@dbsaw YES!! That's exactly it. I really should have thought of that considering I [wrote this article on the subject](https://www.linkedin.com/pulse/how-i-just-customised-my-featured-link-thumbnail-sam-anglin/) 😅

So let's **highlight the above solution** to let whoever takes this on know that it should be a viable way of achieving what we need.

**Comment by MizouziE** [comment]
As an extra, it would be good to use a ternary operator to return the url from `<meta property="og:image" content="**this here url**">` **OR** the nice `energy-price-api-logo` that was so kindly created for us. It's in the `public/images` folder.

**Comment by TAKANOME-DEV** [comment]
After I saw #75 I definitively need to go checkout some regex stuff 😅

**Comment by MizouziE** [comment]
Haha! It's powerful stuff, but takes forever to write 🤯

I'm pretty sure that function does more than necessary, but it was the only way I managed so far to return what I wanted. Hopefully someone will come along and improve it 🤞 

I'll try to work the other bugs out if nobody makes any suggestions, but I'm **definitely** open to suggestions.

**Comment by TAKANOME-DEV** [comment]
It works so that's great 👍 
Yeah for sure go ahead
