### ISSUE TITLE
Results sanitization 

### ISSUE THREAD

**Issue by MizouziE** [MizouziE/energy-prices-api#17]
When certain `sources` are returning results, they sometimes can be formatted in strange ways.
- The Times
![image](https://user-images.githubusercontent.com/90829439/169035969-755720f9-d02a-49be-a910-b01cbe2a661d.png)

It would be good to check for the repetition seen here and remove it. Either:
- Overall character limit on titles
- Regex search of the returned string for '.' and cut it off there

**Comment by ANaphade** [comment]
Consider we have retrieved the title value from the object in titleValue. We can then check for repetition and remove it like below-

const sentences= titleValue.split('.');   //splitting title by '.'
const unique = [...new Set(sentences)].join('.'); //Set will provide us with distinct values in array which we can then join by '.'

**Comment by MizouziE** [comment]
Hi @ANaphade, I see what you mean and it may be possible to work that into the code in `index.js` from line 72 onwards which is currently:
```javascript
sources.forEach(source => {
    axios.get(source.site)
        .then((response) => {
            const html = response.data
            const $ = cheerio.load(html)

            $('a:contains("energy")', html).each(function () {
                const title = $(this).text().replace(/(\r\n|\n|\r)/gm, "").trim()
                const url = $(this).attr('href')

                articles.push({
                    title,
                    url: source.base + url,
                    source: source.name
                })
            })

        })
})
```

Maybe adding it in as a step before `articles.push({...` like the below?
```javascript
sources.forEach(source => {
    axios.get(source.site)
        .then((response) => {
            const html = response.data
            const $ = cheerio.load(html)

            $('a:contains("energy")', html).each(function () {
                const title = $(this).text().replace(/(\r\n|\n|\r)/gm, "").trim()
                const url = $(this).attr('href')

              const sentences= title.split('.'); //splitting title by '.'
              const unique = [...new Set(sentences)].join('.'); //Set will provide us with distinct values in array which we can then join by '.'

                articles.push({
                    title: unique, // You need to set it here
                    url: source.base + url,
                    source: source.name
                })
            })

        })
})
```

I like that this would (theoretically) simply remove repetition and not just cut off after one sentence. I hadn't thought of that. If you'd like to fork the repo, try it out and make a PR I'd be very grateful.

Regardless, I will add you to the contributors list for the discussion as it has certainly added something to the potential solution to this issue.

Thanks!

Sam

**Comment by ANaphade** [comment]
Yes, i'd like to fork the repo and make a PR. Thanks!
