### ISSUE TITLE
Further sanitization

### ISSUE THREAD

**Issue by MizouziE** [MizouziE/energy-prices-api#18]
Linked to #17 

The same culprit source. This time returning an entire `<img...>` tag with far too much info inside.
- ![image](https://user-images.githubusercontent.com/90829439/169036842-42ed0219-2769-4d01-81c5-1863f8f8148b.png)
- Use an `if (...) {} else {}` or `switch` statement to check for this case, then...
- Use a regex function to search string for the `alt="` and return everything after until the closing `"`

**Comment by dcordoba97** [comment]
Hello! Is anyone working on this issue already? If not, I'd love to.

**Comment by MizouziE** [comment]
Hi @dcordoba97 
At the moment no one has this assigned to them, so by all means have at it! Thanks for taking a look. 

I know I already made one suggestion how to handle it, but there's also been a nice suggestion that may give you another idea over on the related issue linked at the top. 

If you have any questions at all I'll be here ASAP. Also I'll assign this issue to you now. 

Looking forward to your input 🙌

**Comment by MizouziE** [comment]
Hi @dcordoba97 ,
I had a chance to test out the `getTitle()` function as some new articles came up with the problem. It turned out that it didn't catch them and they still came through wrapped in `<img>` tags. So I dug around a little and made a few adjustments to what you had already written and I have managed to get it doing what we intended. 

I changed it to the following:
```js
const getTitle = (value) => {
    const altTitle = value.match(/alt=\"(.*?)\"/g);
    if (altTitle == null) return value;
    return altTitle[0].split('"')[1];
}

sources.forEach((source) => {
    axios.get(source.site).then((response) => {
      const html = response.data;
      const $ = cheerio.load(html);
  
      $('a:contains("energy")', html).each(function () {
        const title = getTitle($(this)
            .text()
            .replace(/(\r\n|\n|\r)/gm, "")
            .trim()
      );
```

Seeing as you already did the leg work it's only right I ask if you'd like to make the changes and make another PR? Let's get your GitHub score as high as we can!

If you don't want to, I'm happy to make this an open issue once again so it's totally up to you.

Thanks for getting us going in the right direction in the first place!

**Comment by dcordoba97** [comment]
Hello @MizouziE!

I am glad to hear that my code was useful in some way! I appreciate that you make this proposal. I'll be glad to continue to contribute to your project. Thanks, Sam!
