### ISSUE TITLE
prices

### ISSUE THREAD

**Issue by MizouziE** [MizouziE/energy-prices-api#2]
Add check for "price/prices"

**Comment by MizouziE** [comment]
For now, we are only checking for a single keyword `energy`, perhaps it would be good to have a secondary check to ensure that the articles actually  do relate to the **price** of energy

**Comment by TAKANOME-DEV** [comment]
Oh, that's a good idea. Perhaps it can be an array of keywords ??

**Comment by MizouziE** [comment]
I think that would be good. It would need a little experimentation to see what yields more accurate results.

**Comment by cortezroberto** [comment]
Hello! Is anyone working on this issue already?
I'm interested! :)

**Comment by TAKANOME-DEV** [comment]
I don't think so, give it a shot 👊

**Comment by MizouziE** [comment]
@cortezroberto Please go ahead! We'd be most grateful.
