### ISSUE TITLE
[FEATURE]: add issue template and github workflows

### ISSUE THREAD

**Issue by TAKANOME-DEV** [MizouziE/energy-prices-api#20]
I noticed that there is no `.github` folder. I would like to add one, so contributors can easily report a bug, request a feature, fix type etc.

We can also add worlflows like `codeql-analysis` to analyse the code, use prettier and eslint for code styles and so one...

**Comment by MizouziE** [comment]
This would be a great addition! Please go ahead with what you think is best and put in a PR 🙏

**Comment by TAKANOME-DEV** [comment]
Issue addressed, PR #24 merged
