### ISSUE TITLE
[FEATURE]: Update file structure

### ISSUE THREAD

**Issue by TAKANOME-DEV** [MizouziE/energy-prices-api#21]
As the project grow and even right now, the `index.js` file is getting bigger and bigger.

It could be nice if we can split the code and move the route handler inside a `routes` folder and the business logic inside a `controller` folder.

We can also put the `sources` and `twitterAccounts` inside a json file.

**Comment by MizouziE** [comment]
I absolutely agree and honestly thought I'd made an issue regarding this before but apparently not 😅
Splitting into separate files would be quite a big task so perhaps we can split it into smaller stages? To me it makes the most sense to do in the following order:
1. Sources lists into a .json
2. All routes as they are into a routes.js
3. Then split business logic out into controllers.js

What do you think?

**Comment by TAKANOME-DEV** [comment]
That's a great idea, we can also add a task list so that every time a task is completed, we marked it as resolved.

**Comment by TAKANOME-DEV** [comment]
Can I start working on the first one??

**Comment by MizouziE** [comment]
Yes, by all means

**Comment by MizouziE** [comment]
List of tasks:
- [ ]Sources lists into a .json
- [ ]All routes as they are into a routes.js
- [ ]Then split business logic out into controllers.js

**Comment by TAKANOME-DEV** [comment]
Task 1: done ✔️ 
We can now move to the next 🔥

**Comment by MizouziE** [comment]
Massive thanks to both @TAKANOME-DEV and @Yoshemith for the great work on this big task! 🚀🚀🚀
