### ISSUE TITLE
[CHORE] - Install Prettier dependency 

### ISSUE THREAD

**Issue by MizouziE** [MizouziE/energy-prices-api#31]
### We need the project to have a format standard, so we are choosing Prettier.

- Add prettier as a dependency. [You can find install documentation here](https://prettier.io/docs/en/install.html) 
- Set up basic config file. [Docs here](https://prettier.io/docs/en/configuration.html)
    - I would suggest using the "A `.prettierrc` file written in JSON or YAML." approach
    - The project maintainers will set the needed config up, just create the file with the example setup in the docs.

**Comment by TAKANOME-DEV** [comment]
The `.prettierrc.json` file should contain these minimum config:
```json
{
  "bracketSpacing": true,
  "endOfLine": "lf",
  "singleQuote": true, // or false
  "tabWidth": 2, // or 4
  "useTabs": false
}
```
You can refer to the [docs](https://prettier.io/docs/en/options.html) for information about each option.
@MizouziE let me know if you want to you use `single/double quotes` and `tab width 2/4` and I will edit this before someone start to work on it.

**Comment by MizouziE** [comment]
Let's keep it as you've set it for now and see how it looks. 
Remember I'm a PHP guy, so u don't wanna get into a single/double quote debate with me 😂😂

**Comment by RamonASV** [comment]
Hello! Is anyone working in this issue already? If it is available, may I work on it?

**Comment by MizouziE** [comment]
> Hello! Is anyone working in this issue already? If it is available, may I work on it?

Consider it yours! Thanks for taking it on and we're here if you have any questions.
