### ISSUE TITLE
[OTHER] - add API rate limiting

### ISSUE THREAD

**Issue by MizouziE** [MizouziE/energy-prices-api#34]
### What would you like to share?

Fix API rate limitiing issue as pointed out by @TAKANOME-DEV 

Please comment code to explain reasons for changes that are made for the benefit of later contributors.

### Additional information

```js
app.use((req, res, next) => {
    res.status(404).sendFile(path.resolve('./views/not-found.html'));
})
```
Is the offending code.

**Comment by TAKANOME-DEV** [comment]
> ⚠️  [Snyk Code Security](https://snyk.io/)
> If an endpoint handler performs a file system operation and does not use a rate-limiting mechanism. It may enable the attackers > to perform [Denial-of-service attacks](https://en.wikipedia.org/wiki/Denial-of-service_attack). Consider using a rate-limiting middleware such as [express-rate-limit](https://www.npmjs.com/package/express-rate-limit).

The code above use the `path` module to send the `not-found.html` page when a user go to a url that doesn't exist.
So using that `path` module without limiting the number of request, can lead to a [DoS attack](https://en.wikipedia.org/wiki/Denial-of-service_attack).

We can use [express-rate-limit](https://www.npmjs.com/package/express-rate-limit) package to tacle that issue 🔒 

> 💡  Tip

You can catch those types of vulnerabilities by installing [snyk extension](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner) in vscode.
You can also install the package as an npm dependency to find vulnerabilities on your code and even third-party libraries.

> ❗  Important

Here are [Production Best Practices](https://expressjs.com/en/advanced/best-practice-security.html) recommended by the [Expressjs](https://expressjs.com/) team.
There is also [Performance Best Practices](https://expressjs.com/en/advanced/best-practice-performance.html) for Express applications deployed to production.

Hope this will help 🙏
