### ISSUE TITLE
[FEAT] - Testing with fake HTTP responses

### ISSUE THREAD

**Issue by MizouziE** [MizouziE/energy-prices-api#39]
## Tests
Some unit testing and feature testing would be good to sure up what is added along the way
- In particular something to fake HTTP responses with to ensure all our sanitization methods are doing what they shout be doing

### Possible implementation

A good example was PR #38 
I was unable to confirm that the new method added extracted the article title from within an `<img ... alt="Actual Title">` tag

### Additional information

Perhaps we can keep  **one issue per test** rule to be able to ensure we stay on top of the requirements.

**Comment by TAKANOME-DEV** [comment]
That would be great. Could you create a list of tasks of things that should be tested ??

**Comment by MizouziE** [comment]
> That would be great. Could you create a list of tasks of things that should be tested ??
> 
> And what library do you think we should use ??

Let's go with [Jest](https://jestjs.io/docs/mock-functions) and just get started with a simple "does it give a http response" test to get started and then write up a single issue per test needed from then on.

I found [a nice article](https://zaklaughton.dev/blog/the-only-3-steps-you-need-to-mock-an-api-call-in-jest/) that explains how jest can be used in a similar manner quite nicely to help anyone familiarize themselves with the library.

**Comment by TAKANOME-DEV** [comment]
See that's funny because since this morning, I'm testing a github action with jest and until now I'm struggling to do it 😂 
This article explain it very well, it's a good starter point. Let's do it 💪

**Comment by TAKANOME-DEV** [comment]
There is one thing that I forgot to mention, we have to use [supertest](https://www.npmjs.com/package/supertest) to handle http request to our endpoints.
Here is a quick [video](https://www.youtube.com/watch?v=FKnzS_icp20) on how to use supertest and jest.

**Comment by MizouziE** [comment]
@TAKANOME-DEV that is a great video! Thanks man. I'm used to TDD in Laravel/PHP and had never actually seen an example of it in Node/JS. I really think having those libraries in place will help with future feature development because we're already seeing some great, but complex to build, feature suggestions.

So I propose the following:
-  change this issue to just installing Jest & supertest with the requirement being to write one or two simple tests like the ones demonstrated in the above video link.
- make a seperate issue for each specific test required
- would it be worth creating a `.github/ISSUE_TEMPLATE/test_request.yml` ?

**Comment by TAKANOME-DEV** [comment]
Absolutely we can do that.
* Install jest & supertest and test the main route to make sure that it return index.html
* Each issue ➡️ 1 endpoint
* Sure you can raise a PR and we will discuss about the inputs of that file or create a separate issue for that 

One thing I would like to add is this:

![energy](https://user-images.githubusercontent.com/79809121/170244152-2e7afa49-dced-4288-bbc2-92ee9ea0f2af.png)

As you can this will cause our test file to be bigger and bigger. It would be nice if we move in a `__mocks__/axios.js` file to make our test file clean and readable.
You can learn more about mocking axios using `__mocks__` folder [here](https://www.youtube.com/watch?v=9Yrd4aZkse8)
