### ISSUE TITLE
repeating on single source

### ISSUE THREAD

**Issue by MizouziE** [MizouziE/energy-prices-api#4]
only give one of each result, don't repeat!

The below should only be two results, not 6
![image](https://user-images.githubusercontent.com/90829439/162583156-1e7d8a47-be5e-4470-83d3-8ab1d8203d31.png)

**Comment by TAKANOME-DEV** [comment]
Hi @MizouziE, I want to know where it's happened 🤔

**Comment by MizouziE** [comment]
@TAKANOME-DEV I think it only happens once in a while because the news sources are constantly changing. I have only ever noticed it a few times, but that screenshot above is from one of the worst times 😂

I think we just need some sort of quality control to make sure all is unique. Something similar was mentioned in #7 in a comment that was about ensuring `url: ` was unique.

**Comment by TAKANOME-DEV** [comment]
Interesting, I'm curious about this performance issue though. I hope @nulad will break it down

**Comment by ANaphade** [comment]
I would like to create a PR for this one

**Comment by ANaphade** [comment]
Is anyone working on this issue? If not, I'd like to work on it.

**Comment by MizouziE** [comment]
> Is anyone working on this issue? If not, I'd like to work on it.

@ANaphade At the moment we've figured that a separate issue that is being worked on will fix this, so for the moment it's being investigated/handled. In the case of it not going how we expect, I will assign it to you, but I think it will be solved so I don't want u holding your breath 😄
