### ISSUE TITLE
[CHORE] - Adjust `"license": ...` in `package.json`

### ISSUE THREAD

**Issue by MizouziE** [MizouziE/energy-prices-api#42]
### What work needs to be performed?

Inside the json I forgot to update the license type after a license was actually applied. Can this get updated to reflect the project's actual license type.

### Additional information

Information regarding the type of license [can be found here](https://github.com/MizouziE/energy-prices-api/blob/master/LICENSE.md) or in the `LICENSE.md` file in the project root.

### Hint
It's here 👇
![image](https://user-images.githubusercontent.com/90829439/170033615-d57eb068-e58d-4a9f-ae5a-d753a5fffba0.png)

**Comment by rutterjt** [comment]
Hey there, mind if I fix this?

**Comment by MizouziE** [comment]
@rutterjt It would be much appreciated!
