### ISSUE TITLE
[CHORE] - Clear up the api response

### ISSUE THREAD

**Issue by dbsaw** [MizouziE/energy-prices-api#44]
## I think the response is not clear :
 {"`**/video/ukraine-war-how-does-russia-affect-our-energy-bills-12562454**`":{"title":"How Russia affects our energy bills","url":"https://news.sky.com/video/ukraine-war-how-does-russia-affect-our-energy-bills-12562454","source":"Sky news"}

especially the bolded part I don't get what it means.

## enhancement :
 {"`**How Russia affects our energy bills**`":{"title":"How Russia affects our energy bills","url":"https://news.sky.com/video/ukraine-war-how-does-russia-affect-our-energy-bills-12562454","source":"Sky news"}

easy to fix I hope 🤣.

### like:
 {"`**How Russia affects our energy bills**`":{"title":"How Russia affects our energy bills","url":"https://news.sky.com/video/ukraine-war-how-does-russia-affect-our-energy-bills-12562454","Description":"what ever the article says","picture":"https://coolwebsite.com/pictures/somethingcool.png","source":"Sky news"}

or idk wtvr something like that

**Comment by MizouziE** [comment]
The response keys are currently just the url and this is being used as a kind of `uuid` which fixed a few problems we had early on with repeated results. It would be much tidier with and actual `uuid`, I agree. It may require some form of hashing or uid library to acheive. I could see it "technically" working with bcrypt but I doubt that's very efficient. What other options do you think would be possible?

This issue will be kept open to address the above 👆 

For the image we have a separate issue open for that and I think we may have a solution incoming. 

For the description, I was talking with a friend the other day and he suggested making a sort of *excerpt* from the first paragraph of the article. So I will open a new issue for that too.

**Comment by dbsaw** [comment]
oh ok, know I got it I did not understand the first time sorry.

one solution maybe is using a hash table; I have never used it in my life but I think it will help us here, instead of an ugly extended response.

**Comment by MizouziE** [comment]
@dbsaw 
> Oh ok know I got it I did not understand the first time sorry.
Hey man don't worry at all! We're all here to learn.

I did have a quick look into the uuid package and the one that's built into node.js and they seem to me to create rather long strings so that makes me think we won't be improving very much. I had a look at [short-crypt](https://www.npmjs.com/package/short-crypt), which didn't give an example of it's output on the docs but may be more suitable.

Perhaps you could try it out?
Install the package, require it in the `newsAPIController.js` file and create a `const sc = new ShortCrypt(key);` and then change the following:
```js
        articles[url] = {
          title: uniqueSentences[0],
          url: source.base + url,
          source: source.name,
        };
```
to something like:
```js
        articles[sc.encryptToURLComponent(url)] = {
          title: uniqueSentences[0],
          url: source.base + url,
          source: source.name,
        };
```

Test it out to see how it comes back and if it looks better apply the same thing to the single source article controller too.

Hopefully it will give you back something neater than the entire `url` string while still serving to eliminate repeated instances of the same article as the encryption should give the same string if it is based on the same `url`... in theory. Only one way to find out! 😅

**Comment by dbsaw** [comment]
https://www.npmjs.com/package/short-crypt
tried this but it didn't work cuz it uses CDN

**Comment by MizouziE** [comment]
@dbsaw I'll have to try out what I was thinking to do cos the cdn side shouldn't matter as we only wanna use the installed part server-side. If I figure out a way I'll put it up here.

**Comment by MizouziE** [comment]
I ran `npm i short-crypt` and tried out a few things to see what can be done.

Here is an example of what I was hoping for:
![image](https://user-images.githubusercontent.com/90829439/170888812-adca6469-428c-4af9-b94e-271198488a43.png)

This was achieved in a slightly different way to what I originally proposed which was based on the library's docs. 
- I used `const sc = require('short-crypt')` at the top of the file and invoking a new instance upon calling it each time.
- I used the other available encryption format as it just looks tidier.
- The returned encrypted string was still >80 chars long, so I also used `.slice(0, 10)` to give a shorter looking key.

Ending up with something like:
```js
sources.forEach(async (source) => {
  try {
    const response = await axios.get(source.site);
    const { url, title } = getDataFromCheerio(response.data);
    articles[new sc(url).encryptToQRCodeAlphanumeric(url).slice(0, 10)] = {
      title,
      url: source.base + url,
      source: source.name,
    };
  } catch (error) {
    console.log({ error });
    return;
  }
});
```

**Comment by MizouziE** [comment]
Please see new [branch commit history](https://github.com/MizouziE/energy-prices-api/compare/master...proofs-of-concepts-shortcrypt-and-cheerio-array) for example implementation and subsequent comments explaining steps.

_Please note_: There are changes regarding a separate issue in there too so just worry about the code discussed in the above conversation.

**Comment by dbsaw** [comment]
Yes I think that solved the problem. Is it ok to merge it to the master branch or there is another problem?

**Comment by MizouziE** [comment]
@dbsaw To be honest, I didn't even consider merging that branch as I only wanted to prove it could work somehow. However now that you mention it, it does make sense to just merge it and refactor/improve later as it will eliminate a number of issues. 
Thanks for the idea! I'll make the PR and perhaps you and @TAKANOME-DEV could review it before it is merged?
