### ISSUE TITLE
Change npm run start

### ISSUE THREAD

**Issue by MizouziE** [MizouziE/energy-prices-api#46]
### What is incorrect in the documentation?

We now have nodemon as a development server so we no longer need to use:
```
npm run start
```

### What should that text say?

In the ‘Installation’ section of the README it needs to be replaced with:
```
npm run dev
```

**Comment by anu-codes** [comment]
Hello, can I attempt solving this?

**Comment by TAKANOME-DEV** [comment]
For sure

**Comment by TAKANOME-DEV** [comment]
Close #46
