### ISSUE TITLE
Fix typo in data/sources.json

### ISSUE THREAD

**Issue by MizouziE** [MizouziE/energy-prices-api#48]
### What work needs to be performed?

There is a typo in the name of “The Metro”

### Additional information

![25E964EB-7FEA-4FB8-B2DA-C3A2ED26329D](https://user-images.githubusercontent.com/90829439/170131738-ee51f272-eaa2-474a-901d-a378ad7ada2e.jpeg)

**Comment by NeffCodes** [comment]
Do you mind if I take a crack at this?

**Comment by MizouziE** [comment]
@NeffCodes please be my guest! Thanks a lot!
