### ISSUE TITLE
format titles

### ISSUE THREAD

**Issue by MizouziE** [MizouziE/energy-prices-api#5]
Trim tags and whitespace from beginning of titles

![image](https://user-images.githubusercontent.com/90829439/162583341-09826dbe-0b92-4826-8e8a-7de0e6edbd23.png)

**Comment by OakenSushi** [comment]
@MizouziE 
Hi! 
I am new to contributing to open source projects and would like to work on this issue.
can I work on this issue?

**Comment by MizouziE** [comment]
@OakenSushi absolutely! I will assign it to you ASAP, but feel free to start whenever you want. 

Any questions at all and I'll be here. 

Your input is greatly appreciated 🙏

**Comment by OakenSushi** [comment]
@MizouziE 
Thank you! Ready to create a PR.
Sorry, I don't understand about TBC format, is there any site or PR that can help me with TBC format?

**Comment by MizouziE** [comment]
Create the PR as it is. I only meant the format was not yet decided. TBC = To Be Certified. 

Very glad you asked because I can see that is slightly misleading and I will need to fix it. 

Submit your PR, I'll make a review as soon as I possibly can. Thanks again and I look forward to seeing your solution 🙌
