### ISSUE TITLE
[BUG] errors returned on api routes

### ISSUE THREAD

**Issue by MizouziE** [MizouziE/energy-prices-api#58]
### What bug did you encounter?

visiting /api/news in the browser returns the expected data, but also the following error messages in the terminal:
```sh
[nodemon] starting `node src/app.js`
server running on PORT 8000
Error: ENOENT: no such file or directory, stat '/projects/workspace/views/not-found.html'
Error: ENOENT: no such file or directory, stat '/projects/workspace/views/not-found.html'
Error: ENOENT: no such file or directory, stat '/projects/workspace/views/not-found.html'
Error: ENOENT: no such file or directory, stat '/projects/workspace/views/not-found.html'
Error: ENOENT: no such file or directory, stat '/projects/workspace/views/not-found.html'
Error: ENOENT: no such file or directory, stat '/projects/workspace/views/not-found.html'
```

### What did you expect to happen?

No errors as the route is working as expected.

### Screenshots

All good on this end:
![image](https://user-images.githubusercontent.com/90829439/170474700-90af43f0-291b-4092-9343-4e1f6b7a7e97.png)

### Additional information

The error is caused by code in `./src/server.js`
```js
...
  app.use('/api/news', apiNews);
  app.use('/api/twitter', apiTwitter);
  app.use((req, res, next) => {
    res.status(404).sendFile(path.resolve('./views/not-found.html'));
  });

  return app;
...
```

The above code needs to be:
```js
...
  app.use('/api/news', apiNews);
  app.use('/api/twitter', apiTwitter);
  app.use((req, res, next) => {
    res.status(404).sendFile(path.resolve('./src/views/not-found.html'));
  });

  return app;
...
```

**Comment by TAKANOME-DEV** [comment]
Oh, it seems like I screw up something, would you mind if I take it and try to figure out what's going on here??

**Comment by MizouziE** [comment]
> Oh, it seems like I screwed up something, should it be fixed ASAP or let it for new contributors??

Don't worry about it! All it does is prove that we were right to implement a testing structure!

I would say for this one and the other two relatively easy and similar bugs, leave it and hopefully they are picked up soon by new contributors. The bug in #60 is a little more complex and maybe you'd prefer to fix that one **however** I think it best you take a look *after* these three get cleared up.

**Comment by TAKANOME-DEV** [comment]
Thanks for catching my stupid bugs 😅 
We need to write more tests to prevent these things happening

**Comment by MizouziE** [comment]
@TAKANOME-DEV mate, if we didn't create bugs, it wouldn't be **development**!

**Comment by SquatCub** [comment]
Hello there, could you assign me the issue? I'd like to contribute

**Comment by MizouziE** [comment]
Hi @SquatCub , I have to apologise because this particular issue was handled but the PR was mis-labeled and didn't close the issue. I am going to make a PR shortly and perhaps you wouldn't mind reviewing it before it is merged?
The PR will close a number of the most recent issues, but #27 is still definitely in need of attention if you'd like to take that on, let me know in the comments to assign you. Otherwise, star/watch this repo as I plan to do necessary housekeeping this week and there will be new issues raised, or get yourself familiar with the codebase and raise any issues you find. 

Your input is greatly appreciated!
