### ISSUE TITLE
[DOC] - add contributor code of conduct

### ISSUE THREAD

**Issue by MizouziE** [MizouziE/energy-prices-api#66]
### What is incorrect in the documentation?

This file doesn't exist yet...

We need to make it!

### What should that text say?

You can find the "almost ready to use" text [pre-written in markdown here](https://www.contributor-covenant.org/version/2/0/code_of_conduct/code_of_conduct.md).

Please create a file named `CODE_OF_CONDUCT.md` in the root of the repository, copy the content from the above link and paste it into this new file.

### Additional information

There is a placeholder within the template, so please insert the appropriate info.
- for the reporting you may use my email that is provided in `package.json`

**Comment by alesbe** [comment]
I'll take the issue if you want!
