### ISSUE TITLE
[BUG] Can't find `index.html` when accessing root path on Linux

### ISSUE THREAD

**Issue by alesbe** [MizouziE/energy-prices-api#68]
### What bug did you encounter?

Runing the server with `npm run dev` and accessing `localhost:8000` from the browser, displays the error in the terminal and the browser:

**"Error: ENOENT: no such file or directory, stat '/home/[user]/views/index.html'"**, replacing [user] with the computer user.

### What did you expect to happen?

I expected to see `index.html` when accessing `localhost:8000`

### Screenshots

![error](https://i.imgur.com/Gpxyl55.png)

### Additional information

I'm using Linux, maybe the issue resides in `src/controller/mainController.js` not resolving the path correctly.

Doing `console.log(path.resolve('../views/index.html'))` prints `/home/alesbe/views/index.html`, being `/home/alesbe` my home directory.

And yes, doing `console.log(path.resolve(".."))` from any part of the project prints `/home/alesbe`! It seems like a package issue, not a project issue.

I'll try to look into it, it's weird that this only happens on Linux!

**Comment by alesbe** [comment]
Only happens with the root path, accessing `/api/news` returns the correct data:

![data](https://i.imgur.com/uOqteuB.png)

**Comment by alesbe** [comment]
This workaround seems to fix the issue, but I'm not sure why this happens and if it's only on Linux:

![img](https://i.imgur.com/FuIzO2W.png)

**Comment by MizouziE** [comment]
Yes, it seems that I did a bad code review when closing #57...

My bad, I have re-opened the issue as the solution I proposed in it still stands. And it should be fine for a linux system as I also work on one.

Thanks @alesbe for bringing this to our attention! I will fix it now as it was my fault for missing it.

**Comment by alesbe** [comment]
Great, you can close this one and continue the approach using #57 if you want!
