### ISSUE TITLE
Data structure

### ISSUE THREAD

**Issue by MizouziE** [MizouziE/energy-prices-api#7]
Reconsider structure of sources/articles

![image](https://user-images.githubusercontent.com/90829439/162589739-29aa77f4-a475-4b1f-a9cb-bb5c3f5aafbb.jpeg)

**Comment by nulad** [comment]
I'd like to clarify the purpose of this enhancement. Should we use left one (fastHardToTypeDataStructure) instead of the right one? if so, what should be the unique ID for each item? I propose `url` since it should be unique per news article. What do you think?

**Comment by MizouziE** [comment]
Hi @nulad,
I saw this in a discussion on twitter and was curious as to whether it would improve performance. I certainly wouldn't say, at the stage the project is currently at, that performance is and issue. However I do hope that it grows into something bigger.

>Should we use left one (fastHardToTypeDataStructure) instead of the right one?
- To answer that, yes that is what I'm suggesting.

My main thinking was regarding the `sources` array as this is what is most likely to grow longer and longer, but as it stands, each object does not actually have any `id: uuid_#`. Perhaps adding that would make this idea make more sense, but again, I'm not sure if it would end up making that much difference.

Apart from that, what you suggest about the `url` on the `articles` returned array might actually solve #4 so if you would like to try it out and see what happens it would be great!

**Comment by nulad** [comment]
Yup, my plan was actually to tackle this issue together with #4 since #4 can be solved once we have some kind of id to identify each item. 
My take on the left data structure is the left one is an object with properties, and accessing properties in an object in javascript is fast (O(1) in best case), so accessing items inside should be faster than accessing items inside array.

**Comment by MizouziE** [comment]
Cool! Really happy to have this potential problem addressed way ahead of time. Thanks!

**Comment by nulad** [comment]
I have made a PR for this issue #7 together with #4. Kindly please check it. Thanks!
