### ISSUE TITLE
[BUG] Single source routes broken

### ISSUE THREAD

**Issue by MizouziE** [MizouziE/energy-prices-api#74]
### What bug did you encounter?

The UUID generating logic needs to be copied from the `/news` endpoint controller over to the `/news/:source` controller (single source) controller below it.

Only the `try` block within the `getNewsBySource` method needs altering to the below:
```js
    try {
      const response = await axios.get(sourceSite);
      const returnedArticlesSingle = getDataFromCheerio(response.data);

      returnedArticlesSingle.forEach(async (returnedSingle) => {
        singleSourceArticles[new sc(returnedSingle.url).encryptToQRCodeAlphanumeric(returnedSingle.url).slice(0, 10)] = {
          title: returnedSingle.title,
          url: sourceBase + returnedSingle.url,
          source: sourceName,
        };
      })

```

### What did you expect to happen?

Due to the changes made to the data fetching, this controller was not receiving its expected data. The change outlined above will fix this.

Before it received two distinct params, but now we are proving a single object with a number of params.

### Screenshots

You will end up with endpoints looking like this:
![image](https://user-images.githubusercontent.com/90829439/171884621-2b6dde78-d5e9-4642-9c54-73b8f1d5557c.png)

### Additional information

I've provided a tested solution so that it is just a case of copying and pasting over the current code.

Any questions, just ask and I'll get back to you ASAP.

**Comment by TAKANOME-DEV** [comment]
@MizouziE I'm wondering what happen if someone try to get a single source that does not exist in the `sources.json`??

**Comment by MizouziE** [comment]
Just returns an internal server error on the deployed version atm
![image](https://user-images.githubusercontent.com/90829439/172016720-c5f7bd0c-e9a1-411e-8560-d19b33d1707e.png)

But I haven't checked the most up to date master branch. I think there's a 404 page view somewhere so I think that was set up to be returned, but I'll need to confirm later

**Comment by TAKANOME-DEV** [comment]
That's exactely what I thought.

 In my opinion we should not return a 404 page in such cases but instead we can add a middleware that check if the resource (enter by the user) exist and if not return an explicit error message (and 404 status) to let him know that this particular result does not exist (and avoid unnecessary network request)

Perhaps you can open another issue for open discussion about how we should handle that case

**Comment by MizouziE** [comment]
Very good idea!
