### ISSUE TITLE
[FEAT] - Middleware to handle non-existing source request

### ISSUE THREAD

**Issue by MizouziE** [MizouziE/energy-prices-api#77]
### What feature would you like to see?

A middleware that checks the list of sources and decides whether to proceed with the request or redirect to some kind of response that informs the end user of a bad request (400)

### Possible implementation

Open to discussion

### Additional information

It may involve separating one of the jobs done by the single source controller.

**Comment by MizouziE** [comment]
In development this doesn't seem like a huge issue, but in production it causes the server to crash. We definitely need a safeguard here!
![image](https://user-images.githubusercontent.com/90829439/172652342-c9dda439-0835-4742-8043-c677f8da1abc.png)

**Comment by Yoshemith** [comment]
Hi @MizouziE, I was looking through the project and you're right, it tends to break when there is no existing source. I'd like to work on this issue. I'm thinking of creating a middleware as you described.
