### ISSUE TITLE
[BUG] Broken image for articles from "The Times"

### ISSUE THREAD

**Issue by MizouziE** [MizouziE/energy-prices-api#97]
### What bug did you encounter?

When checking a cool frontend app someone built for this site, I noticed that the articles from "The Times" were not showing an image **or** the back-up image we set.

### What did you expect to happen?

The backup image. (site logo).

### Screenshots

![image](https://user-images.githubusercontent.com/90829439/183269414-54fed2fe-96ad-4997-9397-ade072122b0e.png)

### Additional information

I think we need a better check on the image in the `src/controller/api/newsAPIController.js` file.

Currently it only checks for a `null` and subs in the default image. We need a check to ensure the string starts with `http` _otherwise then_ sub in the default image as that will catch `null` values too.

**Comment by MuizU** [comment]
@MizouziE I'd like to be assigned if possible

**Comment by poljsakerik** [comment]
I can wok on this

**Comment by MizouziE** [comment]
Hi @MuizU & @poljsakerik , I'd be very happy to credit you both on this if you'd like to discuss it between you, create a new branch and both push to it before making the pull request?

Feel free to use this issue as the place to have the discussion.
