### ISSUE TITLE
[BUG] missing URL base for Zee News

### ISSUE THREAD

**Issue by MizouziE** [MizouziE/energy-prices-api#99]
### What bug did you encounter?

Getting the articles back for Zee News, the URLs  are missing the base.

### What did you expect to happen?

Full URL to be returned.

### Screenshots

![image](https://user-images.githubusercontent.com/90829439/183786352-4c72c12f-a37c-4496-803f-4fcd2dd83dbb.png)

### Additional information

Take a look at the structure of the other sources for a hint how to write the `base:` for Zee News.

**Comment by MizouziE** [comment]
## Hint:

Please change `src/data/sources.json` ~line 67 from:
```json
  {
    "name": "Zee News",
    "site": "https://zeenews.india.com/tags/energy-sector.html",
    "base": ""
  }
```

to this:

```json
  {
    "name": "Zee News",
    "site": "https://zeenews.india.com/tags/energy-sector.html",
    "base": "https://zeenews.india.com"
  }
```

**Comment by KetanParmar07** [comment]
Hey, @MizouziE I would like to work on this issue. please assign to me.

**Comment by MizouziE** [comment]
@KetanParmar07 Much appreciated!

**Comment by KetanParmar07** [comment]
What I have  to do?

**Comment by MizouziE** [comment]
> What I have to do?

1. Fork the repository
2. clone your forked repo to your local file system
3. Inside the [`src/data/sources.js`](https://github.com/MizouziE/energy-prices-api/blob/6ba9f6bfcb4682c8670dca16a44228aebb618869/src/data/sources.json) file edit the object for Zee News as described above.
4. Commit the changes
5. Make a Pull Request from your forked repo to this one
6. After reviewing, I'll ask for changes if needed or merge the commit

That should be all, and then I will add you to the list of contributors
